name: uni_shipping
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/abdallah128128/uni_shipping

environment:
  sdk: ^3.2.2

dependencies:
  http: ^1.2.0
  dio: ^5.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
